version: '3.8'
services:
  # nginx:
  #   image: nginx:lts
  #   volumes: 
  #     - ./nginx/:/etc/nginx/conf.d
  #   depends_on: 
  #     - backend

  backend1:
    image: void_back:0.1
    # build: ./Django
    command: bash -c "pip install -r requirements.txt
      && python manage.py makemigrations
      && python manage.py migrate
      && gunicorn bexperts.wsgi --bind :8001"
    volumes:
      - ./Django:/code
    expose:
      - "8001"
    depends_on:
      - db
    restart: always
  
  backend2:
    image: void_back:0.1
    # build: ./Django
    command: bash -c "pip install -r requirements.txt
      && python manage.py makemigrations
      && python manage.py migrate
      && gunicorn bexperts.wsgi --bind :8001"
    volumes:
      - ./Django:/code
    expose:
      - "8002"
    depends_on:
      - db
    restart: always

  db:
    image: mysql
    
    container_name: mysql_service
    environment: 
      MYSQL_ROOT_PASSWORD: "${DB_ROOT_PASSWORD}"
      MYSQL_DATABASE: "${DB_DATABASE}"
      MYSQL_USER: "${DB_USER}"
      MYSQL_PASSWORD: "${DB_PASSWORD}"
    # command: mysqld --character-set-server=utf8 --collation-server=utf8_general_ci
    command: --default-authentication-plugin=mysql_native_password
    security_opt:
      - seccomp:unconfined
    ports:
      - "3306:3306"   
    restart: always

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  nginx:
    image: nginx
    ports:
      - "8005:8005"
    volumes: 
      - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf 
    depends_on:
      - backend1
      - backend2
    # volumes:
    #   - ./nginx/nginx.conf:/etc/nginx/nginx.conf